const context = oEvent.oSource.getBindingContext();  

// Get Entire Model
const data = context.getObject();
var options = {
    data: {id: data.id},
    
};

apiAPI_get_ticket_details(options).then((result)=>{
    //console.log(result)
modelSimpleFormUpdate.setData(result);
})

// Adding data Flexible Column Layout - Mid Column Page

var oFCL = PageList.getParent().getParent();
	oFCL.setLayout(sap.f.LayoutType.TwoColumnsMidExpanded);
